kind: Simple
apiVersion: k3d.io/v1alpha3
name: gitpod
agents: 2
image: k3s
#ports:
#  - port: 8080:80
#    nodeFilters:
#      - loadbalancer
#  - port: 8443:443
#    nodeFilters:
#      - loadbalancer
#  - port: 9500:9500
#    nodeFilters:
#      - loadbalancer
volumes:
  - volume: /usr/src:/usr/src
    nodeFilters:
      - agent:1
  - volume: /etc/hosts:/etc/hosts
    nodeFilters:
      - agent:1
  - volume: /sys/fs/cgroup:/sys/fs/cgroup
    nodeFilters:
      - agent:1
  - volume: /tmp/gitpod:/var/gitpod/workspaces:shared
    nodeFilters:
      - agent:1
options:
  k3d:
    wait: true
    disableLoadbalancer: true
    disableRollback: true
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik
        nodeFilters:
          - server:*
    nodeLabels:
      - label: gitpod.io/workload_meta=true
        nodeFilters:
          - agent:0
      - label: gitpod.io/workload_ide=true
        nodeFilters:
          - agent:0
      - label: gitpod.io/workload_workspace_services=true
        nodeFilters:
          - agent:1
      - label: gitpod.io/workload_workspace_regular=true
        nodeFilters:
          - agent:1
      - label: gitpod.io/workload_workspace_headless=true
        nodeFilters:
          - agent:1
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false
  runtime: {}
